// Generated by gencpp from file amore/NED_objects.msg
// DO NOT EDIT!


#ifndef AMORE_MESSAGE_NED_OBJECTS_H
#define AMORE_MESSAGE_NED_OBJECTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PointStamped.h>

namespace amore
{
template <class ContainerAllocator>
struct NED_objects_
{
  typedef NED_objects_<ContainerAllocator> Type;

  NED_objects_()
    : objects()
    , quantity(0)  {
    }
  NED_objects_(const ContainerAllocator& _alloc)
    : objects(_alloc)
    , quantity(0)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::PointStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::PointStamped_<ContainerAllocator> >::other >  _objects_type;
  _objects_type objects;

   typedef int32_t _quantity_type;
  _quantity_type quantity;





  typedef boost::shared_ptr< ::amore::NED_objects_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::amore::NED_objects_<ContainerAllocator> const> ConstPtr;

}; // struct NED_objects_

typedef ::amore::NED_objects_<std::allocator<void> > NED_objects;

typedef boost::shared_ptr< ::amore::NED_objects > NED_objectsPtr;
typedef boost::shared_ptr< ::amore::NED_objects const> NED_objectsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::amore::NED_objects_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::amore::NED_objects_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::amore::NED_objects_<ContainerAllocator1> & lhs, const ::amore::NED_objects_<ContainerAllocator2> & rhs)
{
  return lhs.objects == rhs.objects &&
    lhs.quantity == rhs.quantity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::amore::NED_objects_<ContainerAllocator1> & lhs, const ::amore::NED_objects_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace amore

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::amore::NED_objects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amore::NED_objects_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amore::NED_objects_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amore::NED_objects_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amore::NED_objects_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amore::NED_objects_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::amore::NED_objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "228b5149963834c6d0e0916fa060e08d";
  }

  static const char* value(const ::amore::NED_objects_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x228b5149963834c6ULL;
  static const uint64_t static_value2 = 0xd0e0916fa060e08dULL;
};

template<class ContainerAllocator>
struct DataType< ::amore::NED_objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "amore/NED_objects";
  }

  static const char* value(const ::amore::NED_objects_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::amore::NED_objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PointStamped[] objects\n"
"int32 quantity\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PointStamped\n"
"# This represents a Point with reference coordinate frame and timestamp\n"
"Header header\n"
"Point point\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::amore::NED_objects_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::amore::NED_objects_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.objects);
      stream.next(m.quantity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NED_objects_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::amore::NED_objects_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::amore::NED_objects_<ContainerAllocator>& v)
  {
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PointStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
    s << indent << "quantity: ";
    Printer<int32_t>::stream(s, indent + "  ", v.quantity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AMORE_MESSAGE_NED_OBJECTS_H
