// Generated by gencpp from file amore/NED_acoustic.msg
// DO NOT EDIT!


#ifndef AMORE_MESSAGE_NED_ACOUSTIC_H
#define AMORE_MESSAGE_NED_ACOUSTIC_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace amore
{
template <class ContainerAllocator>
struct NED_acoustic_
{
  typedef NED_acoustic_<ContainerAllocator> Type;

  NED_acoustic_()
    : points()
    , quantity(0)  {
    }
  NED_acoustic_(const ContainerAllocator& _alloc)
    : points(_alloc)
    , quantity(0)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _points_type;
  _points_type points;

   typedef int32_t _quantity_type;
  _quantity_type quantity;





  typedef boost::shared_ptr< ::amore::NED_acoustic_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::amore::NED_acoustic_<ContainerAllocator> const> ConstPtr;

}; // struct NED_acoustic_

typedef ::amore::NED_acoustic_<std::allocator<void> > NED_acoustic;

typedef boost::shared_ptr< ::amore::NED_acoustic > NED_acousticPtr;
typedef boost::shared_ptr< ::amore::NED_acoustic const> NED_acousticConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::amore::NED_acoustic_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::amore::NED_acoustic_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::amore::NED_acoustic_<ContainerAllocator1> & lhs, const ::amore::NED_acoustic_<ContainerAllocator2> & rhs)
{
  return lhs.points == rhs.points &&
    lhs.quantity == rhs.quantity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::amore::NED_acoustic_<ContainerAllocator1> & lhs, const ::amore::NED_acoustic_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace amore

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::amore::NED_acoustic_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amore::NED_acoustic_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amore::NED_acoustic_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amore::NED_acoustic_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amore::NED_acoustic_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amore::NED_acoustic_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::amore::NED_acoustic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3ccc3a0c67805b14fa25891768bbbb3d";
  }

  static const char* value(const ::amore::NED_acoustic_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3ccc3a0c67805b14ULL;
  static const uint64_t static_value2 = 0xfa25891768bbbb3dULL;
};

template<class ContainerAllocator>
struct DataType< ::amore::NED_acoustic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "amore/NED_acoustic";
  }

  static const char* value(const ::amore::NED_acoustic_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::amore::NED_acoustic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[] points\n"
"int32 quantity\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::amore::NED_acoustic_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::amore::NED_acoustic_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
      stream.next(m.quantity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NED_acoustic_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::amore::NED_acoustic_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::amore::NED_acoustic_<ContainerAllocator>& v)
  {
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
    s << indent << "quantity: ";
    Printer<int32_t>::stream(s, indent + "  ", v.quantity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AMORE_MESSAGE_NED_ACOUSTIC_H
